/**
 * Snowflake Database Schema for Carbon Marketplace Analytics
 * 
 * Run this SQL in Snowflake to create the analytics tables
 * Main operational data is in MongoDB, Snowflake is for analytics/reporting
 */

-- Users table (synced from MongoDB for analytics)
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID VARCHAR(255) PRIMARY KEY,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    IS_BUYER BOOLEAN DEFAULT TRUE,
    IS_SELLER BOOLEAN DEFAULT FALSE,
    RELIABILITY_SCORE NUMBER(5,2),
    CARBON_SAVINGS NUMBER(10,2) DEFAULT 0,
    TOTAL_TRANSACTIONS NUMBER(10) DEFAULT 0,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Buyer Requests (synced from MongoDB)
CREATE TABLE IF NOT EXISTS BUYER_REQUESTS (
    REQUEST_ID VARCHAR(255) PRIMARY KEY,
    BUYER_ID VARCHAR(255) NOT NULL,
    PRODUCT_ID VARCHAR(255) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    QUANTITY NUMBER(10) NOT NULL,
    DESIRED_CARBON_SCORE NUMBER(5,2) NOT NULL,
    MAX_PRICE NUMBER(10,2),
    STATUS VARCHAR(50) NOT NULL,
    AI_SUGGESTED_PRICE NUMBER(10,2),
    AI_SUGGESTED_CARBON_SCORE NUMBER(5,2),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (BUYER_ID) REFERENCES USERS(USER_ID)
);

-- Seller Quotes (synced from MongoDB)
CREATE TABLE IF NOT EXISTS SELLER_QUOTES (
    QUOTE_ID VARCHAR(255) PRIMARY KEY,
    REQUEST_ID VARCHAR(255) NOT NULL,
    SELLER_ID VARCHAR(255) NOT NULL,
    SELLER_NAME VARCHAR(255) NOT NULL,
    SELLER_PRICE NUMBER(10,2) NOT NULL,
    SELLER_CARBON_SCORE NUMBER(5,2) NOT NULL,
    DELIVERY_DAYS NUMBER(5) NOT NULL,
    RELIABILITY_SCORE NUMBER(5,2),
    STATUS VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (REQUEST_ID) REFERENCES BUYER_REQUESTS(REQUEST_ID),
    FOREIGN KEY (SELLER_ID) REFERENCES USERS(USER_ID)
);

-- Transactions (synced from MongoDB)
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    TRANSACTION_ID VARCHAR(255) PRIMARY KEY,
    REQUEST_ID VARCHAR(255) NOT NULL,
    QUOTE_ID VARCHAR(255) NOT NULL,
    BUYER_ID VARCHAR(255) NOT NULL,
    SELLER_ID VARCHAR(255) NOT NULL,
    PRODUCT_ID VARCHAR(255) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    QUANTITY NUMBER(10) NOT NULL,
    FINAL_PRICE NUMBER(10,2) NOT NULL,
    FINAL_CARBON_SCORE NUMBER(5,2) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    SOLANA_SIGNATURE VARCHAR(255),
    BLOCKCHAIN_TX_HASH VARCHAR(255),
    SCC_TOKENS_MINTED NUMBER(10),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT TIMESTAMP_NTZ,
    FOREIGN KEY (REQUEST_ID) REFERENCES BUYER_REQUESTS(REQUEST_ID),
    FOREIGN KEY (QUOTE_ID) REFERENCES SELLER_QUOTES(QUOTE_ID),
    FOREIGN KEY (BUYER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (SELLER_ID) REFERENCES USERS(USER_ID)
);

-- Carbon Savings (analytics table)
CREATE TABLE IF NOT EXISTS CARBON_SAVINGS (
    ID NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID VARCHAR(255) NOT NULL,
    SELLER_ID VARCHAR(255) NOT NULL,
    BUYER_ID VARCHAR(255) NOT NULL,
    PRODUCT_ID VARCHAR(255) NOT NULL,
    CARBON_SCORE NUMBER(5,2) NOT NULL,
    CARBON_SAVED NUMBER(10,2) NOT NULL,
    PRICE NUMBER(10,2) NOT NULL,
    QUANTITY NUMBER(10) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS(TRANSACTION_ID),
    FOREIGN KEY (SELLER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (BUYER_ID) REFERENCES USERS(USER_ID)
);

-- Seller Ratings (analytics table)
CREATE TABLE IF NOT EXISTS SELLER_RATINGS (
    ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SELLER_ID VARCHAR(255) NOT NULL,
    BUYER_ID VARCHAR(255) NOT NULL,
    TRANSACTION_ID VARCHAR(255) NOT NULL,
    RATING NUMBER(2,1) NOT NULL CHECK (RATING >= 1 AND RATING <= 5),
    REVIEW_TEXT VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (SELLER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (BUYER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS(TRANSACTION_ID)
);

-- Product Emissions (analytics table)
CREATE TABLE IF NOT EXISTS PRODUCT_EMISSIONS (
    ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID VARCHAR(255) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    AVG_CARBON_SCORE NUMBER(5,2) NOT NULL,
    TOTAL_QUANTITY NUMBER(10) DEFAULT 0,
    TOTAL_CARBON_SAVED NUMBER(10,2) DEFAULT 0,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Daily Summaries (analytics table)
CREATE TABLE IF NOT EXISTS DAILY_SUMMARIES (
    DATE DATE PRIMARY KEY,
    TOTAL_TRANSACTIONS NUMBER(10) DEFAULT 0,
    TOTAL_CARBON_SAVED NUMBER(10,2) DEFAULT 0,
    TOTAL_VALUE NUMBER(10,2) DEFAULT 0,
    ACTIVE_BUYERS NUMBER(10) DEFAULT 0,
    ACTIVE_SELLERS NUMBER(10) DEFAULT 0,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- User Analytics (overall scoring)
CREATE TABLE IF NOT EXISTS USER_ANALYTICS (
    USER_ID VARCHAR(255) PRIMARY KEY,
    USER_TYPE VARCHAR(10) NOT NULL, -- 'BUYER' or 'SELLER'
    OVERALL_SCORE NUMBER(5,2) NOT NULL,
    QUANTITY_SCORE NUMBER(5,2),
    CARBON_SCORE NUMBER(5,2),
    RELIABILITY_SCORE NUMBER(5,2),
    TRANSACTION_SCORE NUMBER(5,2),
    QUANTITY_PURCHASED NUMBER(10),
    GREEN_CREDITS NUMBER(10,2),
    TOTAL_TRANSACTIONS NUMBER(10),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS IDX_BUYER_REQUESTS_BUYER_ID ON BUYER_REQUESTS(BUYER_ID);
CREATE INDEX IF NOT EXISTS IDX_BUYER_REQUESTS_STATUS ON BUYER_REQUESTS(STATUS);
CREATE INDEX IF NOT EXISTS IDX_SELLER_QUOTES_REQUEST_ID ON SELLER_QUOTES(REQUEST_ID);
CREATE INDEX IF NOT EXISTS IDX_SELLER_QUOTES_SELLER_ID ON SELLER_QUOTES(SELLER_ID);
CREATE INDEX IF NOT EXISTS IDX_TRANSACTIONS_BUYER_ID ON TRANSACTIONS(BUYER_ID);
CREATE INDEX IF NOT EXISTS IDX_TRANSACTIONS_SELLER_ID ON TRANSACTIONS(SELLER_ID);
CREATE INDEX IF NOT EXISTS IDX_TRANSACTIONS_STATUS ON TRANSACTIONS(STATUS);
CREATE INDEX IF NOT EXISTS IDX_CARBON_SAVINGS_CREATED_AT ON CARBON_SAVINGS(CREATED_AT);
CREATE INDEX IF NOT EXISTS IDX_SELLER_RATINGS_SELLER_ID ON SELLER_RATINGS(SELLER_ID);
CREATE INDEX IF NOT EXISTS IDX_USER_ANALYTICS_USER_TYPE ON USER_ANALYTICS(USER_TYPE);
CREATE INDEX IF NOT EXISTS IDX_USER_ANALYTICS_OVERALL_SCORE ON USER_ANALYTICS(OVERALL_SCORE);

